// webf/example/react_use_cases/src/pages/AlertPage.tsx
import React, { useRef } from 'react';
import { createComponent } from '../utils/CreateComponent';
import styles from './AlertPage.module.css';

const WebFListView = createComponent({
  tagName: 'webf-listview',
  displayName: 'WebFListView'
});

const FlutterCupertinoButton = createComponent({
  tagName: 'flutter-cupertino-button',
  displayName: 'FlutterCupertinoButton'
});

const FlutterCupertinoAlert = createComponent({
  tagName: 'flutter-cupertino-alert',
  displayName: 'FlutterCupertinoAlert',
  events: {
    onCancel: 'cancel',
    onConfirm: 'confirm'
  }
});

export const AlertPage: React.FC = () => {
  const basicAlertRef = useRef<any>(null);
  const confirmAlertRef = useRef<any>(null);
  const customAlertRef = useRef<any>(null);
  const destructiveAlertRef = useRef<any>(null);
  const defaultButtonAlertRef = useRef<any>(null);

  const showBasicAlert = () => {
    basicAlertRef.current?.show();
  };

  const showConfirmAlert = () => {
    confirmAlertRef.current?.show();
  };

  const showCustomAlert = () => {
    customAlertRef.current?.show();
  };

  const showDestructiveAlert = () => {
    destructiveAlertRef.current?.show();
  };

  const showDefaultButtonAlert = () => {
    defaultButtonAlertRef.current?.show();
  };

  const onCancel = () => {
    console.log('Operation cancelled');
  };

  const onConfirm = () => {
    console.log('Operation confirmed');
  };

  const onDelete = () => {
    console.log('Executing delete operation');
  };

  const onLater = () => {
    console.log('Postponed');
  };

  const onUpdate = () => {
    console.log('Executing update operation');
  };

  return (
    <div id="main">
      <WebFListView className={styles.list}>
        <div className={styles.componentSection}>
          <div className={styles.sectionTitle}>Alert</div>
          <div className={styles.componentBlock}>
            
            {/* Basic Usage */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>Basic Usage</div>
              <FlutterCupertinoButton variant="filled" onClick={showBasicAlert}>
                Show Basic Alert
              </FlutterCupertinoButton>
            </div>

            {/* With Title and Buttons */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>With Title and Buttons</div>
              <FlutterCupertinoButton variant="filled" onClick={showConfirmAlert}>
                Show Confirm Alert
              </FlutterCupertinoButton>
            </div>

            {/* With Title and Message */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>With Title and Message</div>
              <FlutterCupertinoButton variant="filled" onClick={showCustomAlert}>
                Show Title and Message
              </FlutterCupertinoButton>
            </div>

            {/* Destructive Action */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>Destructive Action</div>
              <FlutterCupertinoButton variant="filled" onClick={showDestructiveAlert}>
                Show Destructive Alert
              </FlutterCupertinoButton>
            </div>

            {/* Default Button */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>Default Button</div>
              <FlutterCupertinoButton variant="filled" onClick={showDefaultButtonAlert}>
                Show Default Button Alert
              </FlutterCupertinoButton>
            </div>
          </div>
        </div>
      </WebFListView>

      {/* Alert Components */}
      <FlutterCupertinoAlert
        ref={basicAlertRef}
        title="This is a Basic Alert"
        confirmText="Got it"
      />

      <FlutterCupertinoAlert 
        ref={confirmAlertRef}
        title="Are you sure you want to proceed?"
        cancelText="Cancel"
        confirmText="Confirm"
        onCancel={onCancel}
        onConfirm={onConfirm}
      />

      <FlutterCupertinoAlert 
        ref={customAlertRef}
        title="Operation Notice"
        message="This is an important notice, please read carefully"
        confirmText="Got it"
      />

      <FlutterCupertinoAlert
        ref={destructiveAlertRef}
        title="Delete Confirmation"
        message="Data cannot be recovered after deletion. Do you want to continue?"
        cancelText="Cancel"
        confirmText="Delete"
        confirmDestructive="true"
        onCancel={onCancel}
        onConfirm={onDelete}
      />

      <FlutterCupertinoAlert
        ref={defaultButtonAlertRef}
        title="Choose Action"
        message="Please select the action to perform"
        cancelText="Later"
        confirmText="Update Now"
        cancelDefault="true"
        onCancel={onLater}
        onConfirm={onUpdate}
      />
    </div>
  );
};

// webf_apps/vue-cupertino-gallery/src/Pages/AlertPage.vue
<template>
  <div id="main">
    <webf-listview id="list">
      <div class="component-section">
        <div class="section-title">Alert</div>
        <div class="component-block">
          <!-- Basic Usage -->
          <div class="component-item">
            <div class="item-label">Basic Usage</div>
            <flutter-cupertino-button variant="filled" @click="showBasicAlert">
              Show Basic Alert
            </flutter-cupertino-button>
          </div>

          <!-- With Title and Buttons -->
          <div class="component-item">
            <div class="item-label">With Title and Buttons</div>
            <flutter-cupertino-button variant="filled" @click="showConfirmAlert">
              Show Confirm Alert
            </flutter-cupertino-button>
          </div>

          <!-- With Title and Message -->
          <div class="component-item">
            <div class="item-label">With Title and Message</div>
            <flutter-cupertino-button variant="filled" @click="showCustomAlert">
              Show Title and Message
            </flutter-cupertino-button>
          </div>

          <!-- Destructive Action -->
          <div class="component-item">
            <div class="item-label">Destructive Action</div>
            <flutter-cupertino-button variant="filled" @click="showDestructiveAlert">
              Show Destructive Alert
            </flutter-cupertino-button>
          </div>

          <!-- Default Button -->
          <div class="component-item">
            <div class="item-label">Default Button</div>
            <flutter-cupertino-button variant="filled" @click="showDefaultButtonAlert">
              Show Default Button Alert
            </flutter-cupertino-button>
          </div>
        </div>
      </div>
    </webf-listview>

    <!-- Alert Components -->
    <flutter-cupertino-alert
      ref="basicAlert"
      title="This is a Basic Alert"
      confirm-text="Got it"
    />

    <flutter-cupertino-alert 
      ref="confirmAlert"
      title="Are you sure you want to proceed?"
      cancel-text="Cancel"
      confirm-text="Confirm"
      @cancel="onCancel"
      @confirm="onConfirm"
    />

    <flutter-cupertino-alert 
      ref="customAlert"
      title="Operation Notice"
      message="This is an important notice, please read carefully"
      confirm-text="Got it"
    />

    <flutter-cupertino-alert
      ref="destructiveAlert"
      title="Delete Confirmation"
      message="Data cannot be recovered after deletion. Do you want to continue?"
      cancel-text="Cancel"
      confirm-text="Delete"
      confirm-destructive="true"
      @cancel="onCancel"
      @confirm="onDelete"
    />

    <flutter-cupertino-alert
      ref="defaultButtonAlert"
      title="Choose Action"
      message="Please select the action to perform"
      cancel-text="Later"
      confirm-text="Update Now"
      cancel-default="true"
      @cancel="onLater"
      @confirm="onUpdate"
    />
  </div>
</template>

<script>
export default {
  methods: {
    showBasicAlert() {
      this.$refs.basicAlert.show();
    },
    showConfirmAlert() {
      this.$refs.confirmAlert.show();
    },
    showCustomAlert() {
      this.$refs.customAlert.show();
    },
    showDestructiveAlert() {
      this.$refs.destructiveAlert.show();
    },
    showDefaultButtonAlert() {
      this.$refs.defaultButtonAlert.show();
    },
    onCancel() {
      console.log('Operation cancelled');
    },
    onConfirm() {
      console.log('Operation confirmed');
    },
    onDelete() {
      console.log('Executing delete operation');
    },
    onLater() {
      console.log('Postponed');
    },
    onUpdate() {
      console.log('Executing update operation');
    }
  }
}
</script>

<style lang="scss" scoped>
#list {
  padding: 10px 0;
  height: 100vh;
  width: 100vw;
  background-color: var(--background-primary);
}

.component-section {
  padding: 16px;
  margin-bottom: 8px;

  .section-title {
    font-size: 20px;
    font-weight: 600;
    color: var(--font-color-primary);
    margin-bottom: 16px;
  }

  .component-block {
    background-color: var(--background-secondary);
    border-radius: 12px;
    padding: 16px;

    .component-item {
      margin-bottom: 24px;

      &:last-child {
        margin-bottom: 0;
      }

      .item-label {
        font-size: 14px;
        color: var(--font-color-secondary);
        margin-bottom: 12px;
      }
    }
  }
}
</style>
