// vue_usecases/src/pages/AlertPage.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { FlutterCupertinoAlertElement } from '@openwebf/vue-cupertino-ui';

const basicAlertRef = ref<FlutterCupertinoAlertElement | null>(null);
const confirmAlertRef = ref<FlutterCupertinoAlertElement | null>(null);
const customAlertRef = ref<FlutterCupertinoAlertElement | null>(null);
const destructiveAlertRef = ref<FlutterCupertinoAlertElement | null>(null);
const defaultButtonAlertRef = ref<FlutterCupertinoAlertElement | null>(null);

function showBasicAlert() {
  basicAlertRef.value?.show({});
}
function showConfirmAlert() {
  confirmAlertRef.value?.show({});
}
function showCustomAlert() {
  customAlertRef.value?.show({});
}
function showDestructiveAlert() {
  destructiveAlertRef.value?.show({});
}
function showDefaultButtonAlert() {
  defaultButtonAlertRef.value?.show({});
}

function onCancel() {
  console.log('Operation cancelled');
}
function onConfirm() {
  console.log('Operation confirmed');
}
function onDelete() {
  console.log('Executing delete operation');
}
function onLater() {
  console.log('Postponed');
}
function onUpdate() {
  console.log('Executing update operation');
}
</script>

<template>
  <div id="main" class="min-h-screen w-full bg-surface">
    <webf-list-view class="w-full px-3 md:px-6 max-w-3xl mx-auto py-6">
      <h1 class="text-2xl font-semibold text-fg-primary mb-4">Alert</h1>
      <div class="flex flex-col gap-4">
        <div class="bg-surface-secondary border border-line rounded-xl p-4">
          <div class="text-lg font-medium text-fg-primary mb-2">Basic Usage</div>
          <flutter-cupertino-button variant="filled" @click="showBasicAlert">Show Basic Alert</flutter-cupertino-button>
        </div>

        <div class="bg-surface-secondary border border-line rounded-xl p-4">
          <div class="text-lg font-medium text-fg-primary mb-2">With Title and Buttons</div>
          <flutter-cupertino-button variant="filled" @click="showConfirmAlert">Show Confirm Alert</flutter-cupertino-button>
        </div>

        <div class="bg-surface-secondary border border-line rounded-xl p-4">
          <div class="text-lg font-medium text-fg-primary mb-2">With Title and Message</div>
          <flutter-cupertino-button variant="filled" @click="showCustomAlert">Show Title and Message</flutter-cupertino-button>
        </div>

        <div class="bg-surface-secondary border border-line rounded-xl p-4">
          <div class="text-lg font-medium text-fg-primary mb-2">Destructive Action</div>
          <flutter-cupertino-button variant="filled" @click="showDestructiveAlert">Show Destructive Alert</flutter-cupertino-button>
        </div>

        <div class="bg-surface-secondary border border-line rounded-xl p-4">
          <div class="text-lg font-medium text-fg-primary mb-2">Default Button</div>
          <flutter-cupertino-button variant="filled" @click="showDefaultButtonAlert">
            Show Default Button Alert
          </flutter-cupertino-button>
        </div>
      </div>
    </webf-list-view>

    <flutter-cupertino-alert ref="basicAlertRef" title="This is a Basic Alert" confirm-text="Got it" />

    <flutter-cupertino-alert
      ref="confirmAlertRef"
      title="Are you sure you want to proceed?"
      cancel-text="Cancel"
      confirm-text="Confirm"
      @cancel="onCancel"
      @confirm="onConfirm"
    />

    <flutter-cupertino-alert
      ref="customAlertRef"
      title="Operation Notice"
      message="This is an important notice, please read carefully"
      confirm-text="Got it"
    />

    <flutter-cupertino-alert
      ref="destructiveAlertRef"
      title="Delete Confirmation"
      message="Data cannot be recovered after deletion. Do you want to continue?"
      cancel-text="Cancel"
      confirm-text="Delete"
      confirm-destructive
      @cancel="onCancel"
      @confirm="onDelete"
    />

    <flutter-cupertino-alert
      ref="defaultButtonAlertRef"
      title="Choose Action"
      message="Please select the action to perform"
      cancel-text="Later"
      confirm-text="Update Now"
      cancel-default
      @cancel="onLater"
      @confirm="onUpdate"
    />
  </div>
</template>

// webf/example/react_use_cases/src/pages/AlertPage.tsx
import React, { useRef } from 'react';
import { createComponent } from '../utils/CreateComponent';
import styles from './AlertPage.module.css';

const WebFListView = createComponent({
  tagName: 'webf-listview',
  displayName: 'WebFListView'
});

const FlutterCupertinoButton = createComponent({
  tagName: 'flutter-cupertino-button',
  displayName: 'FlutterCupertinoButton'
});

const FlutterCupertinoAlert = createComponent({
  tagName: 'flutter-cupertino-alert',
  displayName: 'FlutterCupertinoAlert',
  events: {
    onCancel: 'cancel',
    onConfirm: 'confirm'
  }
});

export const AlertPage: React.FC = () => {
  const basicAlertRef = useRef<any>(null);
  const confirmAlertRef = useRef<any>(null);
  const customAlertRef = useRef<any>(null);
  const destructiveAlertRef = useRef<any>(null);
  const defaultButtonAlertRef = useRef<any>(null);

  const showBasicAlert = () => {
    basicAlertRef.current?.show();
  };

  const showConfirmAlert = () => {
    confirmAlertRef.current?.show();
  };

  const showCustomAlert = () => {
    customAlertRef.current?.show();
  };

  const showDestructiveAlert = () => {
    destructiveAlertRef.current?.show();
  };

  const showDefaultButtonAlert = () => {
    defaultButtonAlertRef.current?.show();
  };

  const onCancel = () => {
    console.log('Operation cancelled');
  };

  const onConfirm = () => {
    console.log('Operation confirmed');
  };

  const onDelete = () => {
    console.log('Executing delete operation');
  };

  const onLater = () => {
    console.log('Postponed');
  };

  const onUpdate = () => {
    console.log('Executing update operation');
  };

  return (
    <div id="main">
      <WebFListView className={styles.list}>
        <div className={styles.componentSection}>
          <div className={styles.sectionTitle}>Alert</div>
          <div className={styles.componentBlock}>
            
            {/* Basic Usage */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>Basic Usage</div>
              <FlutterCupertinoButton variant="filled" onClick={showBasicAlert}>
                Show Basic Alert
              </FlutterCupertinoButton>
            </div>

            {/* With Title and Buttons */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>With Title and Buttons</div>
              <FlutterCupertinoButton variant="filled" onClick={showConfirmAlert}>
                Show Confirm Alert
              </FlutterCupertinoButton>
            </div>

            {/* With Title and Message */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>With Title and Message</div>
              <FlutterCupertinoButton variant="filled" onClick={showCustomAlert}>
                Show Title and Message
              </FlutterCupertinoButton>
            </div>

            {/* Destructive Action */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>Destructive Action</div>
              <FlutterCupertinoButton variant="filled" onClick={showDestructiveAlert}>
                Show Destructive Alert
              </FlutterCupertinoButton>
            </div>

            {/* Default Button */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>Default Button</div>
              <FlutterCupertinoButton variant="filled" onClick={showDefaultButtonAlert}>
                Show Default Button Alert
              </FlutterCupertinoButton>
            </div>
          </div>
        </div>
      </WebFListView>

      {/* Alert Components */}
      <FlutterCupertinoAlert
        ref={basicAlertRef}
        title="This is a Basic Alert"
        confirmText="Got it"
      />

      <FlutterCupertinoAlert 
        ref={confirmAlertRef}
        title="Are you sure you want to proceed?"
        cancelText="Cancel"
        confirmText="Confirm"
        onCancel={onCancel}
        onConfirm={onConfirm}
      />

      <FlutterCupertinoAlert 
        ref={customAlertRef}
        title="Operation Notice"
        message="This is an important notice, please read carefully"
        confirmText="Got it"
      />

      <FlutterCupertinoAlert
        ref={destructiveAlertRef}
        title="Delete Confirmation"
        message="Data cannot be recovered after deletion. Do you want to continue?"
        cancelText="Cancel"
        confirmText="Delete"
        confirmDestructive="true"
        onCancel={onCancel}
        onConfirm={onDelete}
      />

      <FlutterCupertinoAlert
        ref={defaultButtonAlertRef}
        title="Choose Action"
        message="Please select the action to perform"
        cancelText="Later"
        confirmText="Update Now"
        cancelDefault="true"
        onCancel={onLater}
        onConfirm={onUpdate}
      />
    </div>
  );
};
