// vue_usecases/src/pages/cupertino/CupertinoTabsPage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { CupertinoIcons, CupertinoColors } from '@openwebf/vue-cupertino-ui';

const basicTabIndex = ref(0);
const scaffoldTabIndex = ref(0);
const navTabIndex = ref(0);
</script>

<template>
  <div id="main" class="min-h-screen w-full bg-surface">
    <webf-list-view class="w-full px-3 md:px-6 max-w-4xl mx-auto py-6">
      <h1 class="text-2xl md:text-3xl font-semibold text-fg-primary mb-4">Cupertino Tabs</h1>
      <p class="text-fg-secondary mb-6">iOS-style tab bars, scaffolds, and per-tab navigation.</p>

      <section class="mb-8">
        <h2 class="text-xl font-semibold text-fg-primary mb-3">Basic TabBar</h2>
        <p class="text-fg-secondary mb-4">A standalone bottom tab bar that drives an index.</p>

        <div class="bg-surface-secondary rounded-xl p-6 border border-line mb-4">
          <div class="bg-white rounded-lg h-[300px] relative overflow-hidden">
            <div class="p-6 text-center">
              <h3 class="text-lg font-semibold mb-2">Selected Tab: {{ basicTabIndex }}</h3>
              <p class="text-gray-600">
                <span v-if="basicTabIndex === 0">Home content</span>
                <span v-else-if="basicTabIndex === 1">Search content</span>
                <span v-else>Profile content</span>
              </p>
            </div>

            <div class="absolute bottom-0 left-0 right-0">
              <flutter-cupertino-tab-bar
                :current-index="basicTabIndex"
                :active-color="CupertinoColors.activeBlue"
                @change="(e) => (basicTabIndex = e.detail)"
              >
                <flutter-cupertino-tab-bar-item title="Home">
                  <flutter-cupertino-icon :type="CupertinoIcons.house_fill" />
                </flutter-cupertino-tab-bar-item>
                <flutter-cupertino-tab-bar-item title="Search">
                  <flutter-cupertino-icon :type="CupertinoIcons.search" />
                </flutter-cupertino-tab-bar-item>
                <flutter-cupertino-tab-bar-item title="Profile">
                  <flutter-cupertino-icon :type="CupertinoIcons.person_fill" />
                </flutter-cupertino-tab-bar-item>
              </flutter-cupertino-tab-bar>
            </div>
          </div>
        </div>
      </section>

      <section class="mb-8">
        <h2 class="text-xl font-semibold text-fg-primary mb-3">TabScaffold</h2>
        <p class="text-fg-secondary mb-4">A complete tab layout with integrated bottom bar and per-tab content.</p>

        <div class="bg-surface-secondary rounded-xl p-6 border border-line mb-4">
          <div class="bg-white rounded-lg h-[420px] overflow-hidden">
            <flutter-cupertino-tab-scaffold class="h-full" :current-index="scaffoldTabIndex" @change="(e) => (scaffoldTabIndex = e.detail)">
              <flutter-cupertino-tab-scaffold-tab title="Home">
                <flutter-cupertino-icon :type="CupertinoIcons.house_fill" />
                <div class="p-6">
                  <h3 class="text-lg font-semibold mb-2">Home</h3>
                  <p class="text-gray-600 mb-4">Welcome to the home tab.</p>
                  <div class="space-y-2">
                    <div class="bg-blue-50 p-4 rounded-lg">Recent Activity</div>
                    <div class="bg-blue-50 p-4 rounded-lg">Quick Actions</div>
                    <div class="bg-blue-50 p-4 rounded-lg">News Feed</div>
                  </div>
                </div>
              </flutter-cupertino-tab-scaffold-tab>

              <flutter-cupertino-tab-scaffold-tab title="Favorites">
                <flutter-cupertino-icon :type="CupertinoIcons.star_fill" />
                <div class="p-6">
                  <h3 class="text-lg font-semibold mb-2">Favorites</h3>
                  <p class="text-gray-600 mb-4">Your saved items appear here.</p>
                  <div class="space-y-2">
                    <div class="bg-yellow-50 p-4 rounded-lg flex items-center gap-2">
                      <flutter-cupertino-icon :type="CupertinoIcons.star_fill" />
                      <span>Favorite Item 1</span>
                    </div>
                    <div class="bg-yellow-50 p-4 rounded-lg flex items-center gap-2">
                      <flutter-cupertino-icon :type="CupertinoIcons.star_fill" />
                      <span>Favorite Item 2</span>
                    </div>
                    <div class="bg-yellow-50 p-4 rounded-lg flex items-center gap-2">
                      <flutter-cupertino-icon :type="CupertinoIcons.star_fill" />
                      <span>Favorite Item 3</span>
                    </div>
                  </div>
                </div>
              </flutter-cupertino-tab-scaffold-tab>

              <flutter-cupertino-tab-scaffold-tab title="Gallery">
                <flutter-cupertino-icon :type="CupertinoIcons.photo_fill" />
                <div class="p-6">
                  <h3 class="text-lg font-semibold mb-2">Gallery</h3>
                  <p class="text-gray-600 mb-4">A simple grid preview.</p>
                  <div class="flex flex-wrap gap-3">
                    <div v-for="i in 9" :key="i" class="bg-purple-100 aspect-square rounded-lg flex items-center justify-center w-[90px]">
                      <flutter-cupertino-icon :type="CupertinoIcons.photo_fill" />
                    </div>
                  </div>
                </div>
              </flutter-cupertino-tab-scaffold-tab>
            </flutter-cupertino-tab-scaffold>
          </div>
        </div>
      </section>

      <section class="mb-8">
        <h2 class="text-xl font-semibold text-fg-primary mb-3">TabView (Per-Tab Navigation)</h2>
        <p class="text-fg-secondary mb-4">Each tab can host its own navigation stack using <code>TabView</code>.</p>

        <div class="bg-surface-secondary rounded-xl p-6 border border-line mb-4">
          <div class="bg-white rounded-lg overflow-hidden h-[420px]">
            <flutter-cupertino-tab-scaffold class="h-full" :current-index="navTabIndex" @change="(e) => (navTabIndex = e.detail)">
              <flutter-cupertino-tab-scaffold-tab title="Feed">
                <flutter-cupertino-icon :type="CupertinoIcons.rectangle_stack_fill" />
                <flutter-cupertino-tab-view default-title="Feed">
                  <div class="p-6">
                    <h3 class="text-lg font-semibold mb-2">Activity Feed</h3>
                    <p class="text-gray-600 mb-4">This view maintains its own navigation stack (handled by Flutter).</p>
                    <div class="space-y-2">
                      <div v-for="i in 3" :key="i" class="bg-indigo-50 p-4 rounded-lg border-l-4 border-indigo-500">
                        <div class="font-semibold">Update {{ i }}</div>
                        <div class="text-sm text-gray-600">Tap interactions are handled inside the tab view.</div>
                      </div>
                    </div>
                  </div>
                </flutter-cupertino-tab-view>
              </flutter-cupertino-tab-scaffold-tab>

              <flutter-cupertino-tab-scaffold-tab title="Account">
                <flutter-cupertino-icon :type="CupertinoIcons.person_crop_circle" />
                <flutter-cupertino-tab-view default-title="Account">
                  <div class="p-6">
                    <h3 class="text-lg font-semibold mb-2">Account</h3>
                    <p class="text-gray-600 mb-4">A second navigation stack in a different tab.</p>
                    <div class="space-y-2">
                      <div class="bg-gray-50 p-4 rounded-lg flex items-center justify-between">
                        <div>
                          <div class="font-semibold">Profile</div>
                          <div class="text-sm text-gray-600">Manage your profile</div>
                        </div>
                        <flutter-cupertino-icon :type="CupertinoIcons.chevron_right" />
                      </div>
                      <div class="bg-gray-50 p-4 rounded-lg flex items-center justify-between">
                        <div>
                          <div class="font-semibold">Settings</div>
                          <div class="text-sm text-gray-600">Preferences</div>
                        </div>
                        <flutter-cupertino-icon :type="CupertinoIcons.chevron_right" />
                      </div>
                    </div>
                  </div>
                </flutter-cupertino-tab-view>
              </flutter-cupertino-tab-scaffold-tab>
            </flutter-cupertino-tab-scaffold>
          </div>
        </div>
      </section>
    </webf-list-view>
  </div>
</template>

// use_cases/src/pages/cupertino/CupertinoTabsPage.tsx
import React, {useState} from 'react';
import {WebFListView} from '@openwebf/react-core-ui';
import {
  FlutterCupertinoTabBar,
  FlutterCupertinoTabBarItem,
  FlutterCupertinoTabScaffold,
  FlutterCupertinoTabScaffoldTab,
  FlutterCupertinoTabView,
  FlutterCupertinoIcon,
  CupertinoIcons, CupertinoColors,
} from '@openwebf/react-cupertino-ui';

export const CupertinoTabsPage: React.FC = () => {
  const [basicTabIndex, setBasicTabIndex] = useState(0);
  const [scaffoldTabIndex, setScaffoldTabIndex] = useState(0);
  const [customTabIndex, setCustomTabIndex] = useState(0);
  const [navTabIndex, setNavTabIndex] = useState(0);
  return (
    <div id="main" className="min-h-screen w-full bg-surface">
      <WebFListView className="w-full px-3 md:px-6 max-w-4xl mx-auto py-6">
          <h1 className="text-2xl md:text-3xl font-semibold text-fg-primary mb-4">Cupertino Tabs</h1>
          <p className="text-fg-secondary mb-6">iOS-style tab bars, scaffolds, and per-tab navigation.</p>

          {/* Basic TabBar */}
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-fg-primary mb-3">Basic TabBar</h2>
            <p className="text-fg-secondary mb-4">A standalone bottom navigation bar with items.</p>

            <div className="bg-surface-secondary rounded-xl p-6 border border-line mb-4">
              <div className="bg-white rounded-lg h-[300px] relative">
                <div className="p-6 text-center">
                  <h3 className="text-lg font-semibold mb-2">Selected Tab: {basicTabIndex}</h3>
                  <p className="text-gray-600">
                    {basicTabIndex === 0 && 'Home content'}
                    {basicTabIndex === 1 && 'Search content'}
                    {basicTabIndex === 2 && 'Profile content'}
                  </p>
                </div>

                <div className="absolute bottom-0 left-0 right-0">
                  <FlutterCupertinoTabBar
                    currentIndex={basicTabIndex}
                    onChange={(e) => setBasicTabIndex(e.detail)}
                  >
                    <FlutterCupertinoTabBarItem title="Home">
                      <FlutterCupertinoIcon type={CupertinoIcons.house_fill}/>
                    </FlutterCupertinoTabBarItem>
                    <FlutterCupertinoTabBarItem title="Search">
                      <FlutterCupertinoIcon type={CupertinoIcons.search}/>
                    </FlutterCupertinoTabBarItem>
                    <FlutterCupertinoTabBarItem title="Profile">
                      <FlutterCupertinoIcon type={CupertinoIcons.person_fill}/>
                    </FlutterCupertinoTabBarItem>
                  </FlutterCupertinoTabBar>
                </div>
              </div>
            </div>
          </section>

          {/* TabScaffold Basic */}
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-fg-primary mb-3">TabScaffold</h2>
            <p className="text-fg-secondary mb-4">Complete tab interface with integrated bottom bar and content areas.</p>

            <div className="bg-surface-secondary rounded-xl p-6 border border-line mb-4">
              <div className="bg-white rounded-lg h-[400px]">
                <FlutterCupertinoTabScaffold
                  className="h-full"
                  currentIndex={scaffoldTabIndex}
                  onChange={(e) => setScaffoldTabIndex(e.detail)}
                >
                  <FlutterCupertinoTabScaffoldTab title="Home">
                    <FlutterCupertinoIcon type={CupertinoIcons.house_fill}/>
                    <div className="p-6">
                      <h3 className="text-lg font-semibold mb-2">Home</h3>
                      <p className="text-gray-600 mb-4">Welcome to the home tab.</p>
                      <div className="space-y-2">
                        <div className="bg-blue-50 p-4 rounded-lg">Recent Activity</div>
                        <div className="bg-blue-50 p-4 rounded-lg">Quick Actions</div>
                        <div className="bg-blue-50 p-4 rounded-lg">News Feed</div>
                      </div>
                    </div>
                  </FlutterCupertinoTabScaffoldTab>

                  <FlutterCupertinoTabScaffoldTab title="Favorites">
                    <FlutterCupertinoIcon type={CupertinoIcons.star_fill}/>
                    <div className="p-6">
                      <h3 className="text-lg font-semibold mb-2">Favorites</h3>
                      <p className="text-gray-600 mb-4">Your saved items appear here.</p>
                      <div className="space-y-2">
                        <div className="bg-yellow-50 p-4 rounded-lg flex items-center">
                          <FlutterCupertinoIcon type={CupertinoIcons.star_fill} className="text-2xl mr-3"/>
                          <span>Favorite Item 1</span>
                        </div>
                        <div className="bg-yellow-50 p-4 rounded-lg flex items-center">
                          <FlutterCupertinoIcon type={CupertinoIcons.star_fill} className="text-2xl mr-3"/>
                          <span>Favorite Item 2</span>
                        </div>
                      </div>
                    </div>
                  </FlutterCupertinoTabScaffoldTab>

                  <FlutterCupertinoTabScaffoldTab title="Settings">
                    <FlutterCupertinoIcon type={CupertinoIcons.gear_alt_fill}/>
                    <div className="p-6">
                      <h3 className="text-lg font-semibold mb-2">Settings</h3>
                      <p className="text-gray-600 mb-4">Manage your preferences.</p>
                      <div className="space-y-2">
                        <div className="bg-gray-50 p-4 rounded-lg">Account Settings</div>
                        <div className="bg-gray-50 p-4 rounded-lg">Privacy & Security</div>
                        <div className="bg-gray-50 p-4 rounded-lg">Notifications</div>
                        <div className="bg-gray-50 p-4 rounded-lg">About</div>
                      </div>
                    </div>
                  </FlutterCupertinoTabScaffoldTab>
                </FlutterCupertinoTabScaffold>
              </div>
            </div>
          </section>

          {/* TabScaffold with Custom TabBar */}
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-fg-primary mb-3">TabScaffold with Custom TabBar</h2>
            <p className="text-fg-secondary mb-4">Customize tab bar appearance with colors, icon size, and border.</p>

            <div className="bg-surface-secondary rounded-xl p-6 border border-line mb-4">
              <div className="bg-white rounded-lg h-[400px]">
                <FlutterCupertinoTabScaffold
                  className="h-full"
                  currentIndex={customTabIndex}
                  onChange={(e) => setCustomTabIndex(e.detail)}
                >
                  <FlutterCupertinoTabBar
                    backgroundColor={CupertinoColors.systemGrey6}
                    activeColor={CupertinoColors.systemBlue}
                    inactiveColor={CupertinoColors.inactiveGray}
                    iconSize={32}
                    noTopBorder={false}
                  >
                    <FlutterCupertinoTabBarItem title="Chat">
                      <FlutterCupertinoIcon type={CupertinoIcons.bubble_left_bubble_right_fill}/>
                    </FlutterCupertinoTabBarItem>
                    <FlutterCupertinoTabBarItem title="Photos">
                      <FlutterCupertinoIcon type={CupertinoIcons.photo_fill}/>
                    </FlutterCupertinoTabBarItem>
                    <FlutterCupertinoTabBarItem title="Music">
                      <FlutterCupertinoIcon type={CupertinoIcons.music_note_2}/>
                    </FlutterCupertinoTabBarItem>
                  </FlutterCupertinoTabBar>

                  <FlutterCupertinoTabScaffoldTab title="Chat">
                    <div className="p-6 h-full overflow-auto">
                      <h3 className="text-lg font-semibold mb-2">Messages</h3>
                      <p className="text-gray-600 mb-4">Your conversations.</p>
                      <div className="space-y-2 overflow-auto">
                        <div className="bg-blue-50 p-4 rounded-lg flex items-center gap-2">
                          <FlutterCupertinoIcon type={CupertinoIcons.bubble_left_bubble_right_fill}/>
                          <span>John Doe</span>
                        </div>
                        <div className="bg-blue-50 p-4 rounded-lg flex items-center gap-2">
                          <FlutterCupertinoIcon type={CupertinoIcons.bubble_left_bubble_right_fill}/>
                          <span>Jane Smith</span>
                        </div>
                        <div className="bg-blue-50 p-4 rounded-lg flex items-center gap-2">
                          <FlutterCupertinoIcon type={CupertinoIcons.bubble_left_bubble_right_fill}/>
                          <span>Team Chat</span>
                        </div>
                      </div>
                    </div>
                  </FlutterCupertinoTabScaffoldTab>

                  <FlutterCupertinoTabScaffoldTab title="Photos">
                    <div className="p-6 h-full overflow-auto">
                      <h3 className="text-lg font-semibold mb-2">Photo Library</h3>
                      <p className="text-gray-600 mb-4">Your photo collection.</p>
                      <div className="flex flex-wrap gap-2">
                        <div className="bg-purple-100 aspect-square rounded-lg flex items-center justify-center w-1/3">
                          <FlutterCupertinoIcon type={CupertinoIcons.photo_fill}/>
                        </div>
                        <div className="bg-purple-100 aspect-square rounded-lg flex items-center justify-center w-1/3">
                          <FlutterCupertinoIcon type={CupertinoIcons.photo_fill}/>
                        </div>
                        <div className="bg-purple-100 aspect-square rounded-lg flex items-center justify-center w-1/3">
                          <FlutterCupertinoIcon type={CupertinoIcons.photo_fill}/>
                        </div>
                        <div className="bg-purple-100 aspect-square rounded-lg flex items-center justify-center w-1/3">
                          <FlutterCupertinoIcon type={CupertinoIcons.photo_fill}/>
                        </div>
                        <div className="bg-purple-100 aspect-square rounded-lg flex items-center justify-center w-1/3">
                          <FlutterCupertinoIcon type={CupertinoIcons.photo_fill}/>
                        </div>
                        <div className="bg-purple-100 aspect-square rounded-lg flex items-center justify-center w-1/3">
                          <FlutterCupertinoIcon type={CupertinoIcons.photo_fill}/>
                        </div>
                      </div>
                    </div>
                  </FlutterCupertinoTabScaffoldTab>

                  <FlutterCupertinoTabScaffoldTab title="Music">
                    <div className="p-6 h-full overflow-auto">
                      <h3 className="text-lg font-semibold mb-2">Music Player</h3>
                      <p className="text-gray-600 mb-4">Your music library.</p>
                      <div className="space-y-2">
                        <div className="bg-pink-50 p-4 rounded-lg flex items-center gap-2">
                          <FlutterCupertinoIcon type={CupertinoIcons.music_note_2}/>
                          <span>Recently Played</span>
                        </div>
                        <div className="bg-pink-50 p-4 rounded-lg flex items-center gap-2">
                          <FlutterCupertinoIcon type={CupertinoIcons.music_note_2}/>
                          <span>Playlists</span>
                        </div>
                        <div className="bg-pink-50 p-4 rounded-lg flex items-center gap-2">
                          <FlutterCupertinoIcon type={CupertinoIcons.music_note_2}/>
                          <span>Albums</span>
                        </div>
                      </div>
                    </div>
                  </FlutterCupertinoTabScaffoldTab>
                </FlutterCupertinoTabScaffold>
              </div>
            </div>
          </section>

          {/* TabView with Navigation */}
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-fg-primary mb-3">TabView with Per-Tab Navigation</h2>
            <p className="text-fg-secondary mb-4">Each tab maintains its own navigation stack using TabView.</p>

            <div className="bg-surface-secondary rounded-xl p-6 border border-line mb-4">
              <div className="bg-white rounded-lg overflow-hidden h-[400px]">
                <FlutterCupertinoTabScaffold
                  className="h-full"
                  currentIndex={navTabIndex}
                  onChange={(e) => setNavTabIndex(e.detail)}
                >
                  <FlutterCupertinoTabScaffoldTab title="Feed">
                    <FlutterCupertinoIcon type={CupertinoIcons.rectangle_stack_fill}/>
                    <FlutterCupertinoTabView defaultTitle="Feed">
                      <div className="p-6">
                        <h3 className="text-lg font-semibold mb-2">Activity Feed</h3>
                        <p className="text-gray-600 mb-4">Latest updates with navigation support.</p>
                        <div className="space-y-2">
                          <div className="bg-indigo-50 p-4 rounded-lg border-l-4 border-indigo-500">
                            <div className="font-semibold">Update 1</div>
                            <div className="text-sm text-gray-600">Navigate to details →</div>
                          </div>
                          <div className="bg-indigo-50 p-4 rounded-lg border-l-4 border-indigo-500">
                            <div className="font-semibold">Update 2</div>
                            <div className="text-sm text-gray-600">Navigate to details →</div>
                          </div>
                          <div className="bg-indigo-50 p-4 rounded-lg border-l-4 border-indigo-500">
                            <div className="font-semibold">Update 3</div>
                            <div className="text-sm text-gray-600">Navigate to details →</div>
                          </div>
                        </div>
                      </div>
                    </FlutterCupertinoTabView>
                  </FlutterCupertinoTabScaffoldTab>

                  <FlutterCupertinoTabScaffoldTab title="Account">
                    <FlutterCupertinoIcon type={CupertinoIcons.person_crop_circle_fill}/>
                    <FlutterCupertinoTabView defaultTitle="Account">
                      <div className="p-6">
                        <h3 className="text-lg font-semibold mb-2">Your Account</h3>
                        <p className="text-gray-600 mb-4">Account settings with independent navigation.</p>
                        <div className="space-y-2">
                          <div className="bg-green-50 p-4 rounded-lg">Profile Information</div>
                          <div className="bg-green-50 p-4 rounded-lg">Security Settings</div>
                          <div className="bg-green-50 p-4 rounded-lg">Subscription</div>
                          <div className="bg-green-50 p-4 rounded-lg">Billing History</div>
                        </div>
                      </div>
                    </FlutterCupertinoTabView>
                  </FlutterCupertinoTabScaffoldTab>
                </FlutterCupertinoTabScaffold>
              </div>
            </div>
          </section>

          {/* Props Reference */}
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-fg-primary mb-3">Props Reference</h2>

            <div className="bg-surface-secondary rounded-xl p-6 border border-line space-y-6">
              <div>
                <h3 className="font-semibold text-fg-primary mb-2">FlutterCupertinoTabBar</h3>
                <ul className="space-y-1 text-sm text-fg-secondary">
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">currentIndex</code> — Active tab index (number)</li>
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">backgroundColor</code> — Hex color (#RRGGBB or #AARRGGBB)</li>
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">activeColor</code> — Active item color</li>
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">inactiveColor</code> — Inactive items color</li>
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">iconSize</code> — Icon size in pixels</li>
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">noTopBorder</code> — Remove top border (boolean)</li>
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">onChange</code> — Selection change event</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold text-fg-primary mb-2">FlutterCupertinoTabScaffold</h3>
                <ul className="space-y-1 text-sm text-fg-secondary">
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">currentIndex</code> — Active tab index (number)</li>
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">resizeToAvoidBottomInset</code> — Reserved for parity (boolean)</li>
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">onChange</code> — Tab change event (e.detail contains index)</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold text-fg-primary mb-2">FlutterCupertinoTabView</h3>
                <ul className="space-y-1 text-sm text-fg-secondary">
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">defaultTitle</code> — Default Navigator title (string)</li>
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">restorationScopeId</code> — State restoration ID (string)</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold text-fg-primary mb-2">FlutterCupertinoTabBarItem</h3>
                <ul className="space-y-1 text-sm text-fg-secondary">
                  <li><code className="bg-gray-100 px-2 py-0.5 rounded">title</code> — Label below the icon (string)</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Notes */}
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-fg-primary mb-3">Notes</h2>
            <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded">
              <ul className="space-y-2 text-sm text-gray-700">
                <li><strong>TabBar</strong> can be used standalone or nested in TabScaffold for appearance customization</li>
                <li><strong>TabScaffold</strong> uses IndexedStack to keep off-screen tabs alive (state persists)</li>
                <li><strong>TabView</strong> provides per-tab Navigator for independent navigation stacks</li>
                <li>Event <code>change</code> maps to <code>onChange</code> in React with index in <code>event.detail</code></li>
                <li>Keep TabScaffoldTab count/order in sync with TabBarItem when using nested TabBar</li>
              </ul>
            </div>
          </section>
      </WebFListView>
    </div>
  );
};
