// vue_usecases/src/pages/css/BGImagePage.vue
<script setup lang="ts">
const flower = new URL('../../resource/bg_flower.gif', import.meta.url).href;
const webfPng = new URL('../../resource/webf.png', import.meta.url).href;

const containerBase = {
  margin: '5px',
  textAlign: 'center',
  borderColor: 'red',
  borderWidth: '5px',
  padding: '5px',
  borderStyle: 'solid',
  width: '50%',
  height: '100px',
} as const;
</script>

<template>
  <div id="main">
    <webf-list-view class="p-5 m-0 bg-[#f8f9fa]" :style="{ height: '480px', flexDirection: 'column' }">
      <div
        :style="{
          ...containerBase,
          backgroundImage: `url(${flower})`,
          backgroundOrigin: 'content-box',
          backgroundPosition: 'left top',
          backgroundRepeat: 'no-repeat',
        }"
      />

      <div
        :style="{
          ...containerBase,
          backgroundImage: `url(${flower})`,
          backgroundOrigin: 'padding-box',
          backgroundPosition: '50% 50%',
          backgroundRepeat: 'repeat-x',
        }"
      />

      <div
        :style="{
          ...containerBase,
          backgroundImage: `url(${flower})`,
          backgroundOrigin: 'border-box',
          backgroundPosition: '30px 40px',
          backgroundRepeat: 'repeat',
        }"
      />

      <div
        :style="{
          ...containerBase,
          backgroundImage: `url(${flower}), url(${webfPng})`,
          backgroundOrigin: 'content-box, border-box',
          backgroundPosition: '50% 40px, right bottom',
          backgroundRepeat: 'repeat-y, repeat-x',
        }"
      />
    </webf-list-view>
  </div>
</template>

// webf_apps/react_use_cases/src/pages/css/BGImagePage.tsx
import React from 'react';
import { WebFListView } from '@openwebf/react-core-ui';
import styles from './BGImagePage.module.css';

export const BGImagePage: React.FC = () => {
  return (
    <div id="main">
      <WebFListView className={styles.list}>
        <div className={styles.fixedArea}>
          <div
            className={`${styles.container} ${styles.image1}`}
            style={{
              backgroundOrigin: "content-box",
              backgroundPosition: "left top",
              backgroundRepeat: "no-repeat",
            }}
          >
          </div>

          <div
            className={`${styles.container} ${styles.image1}`}
            style={{
              backgroundOrigin: "padding-box",
              backgroundPosition: "50% 50%",
              backgroundRepeat: "repeat-x",
            }}
          >
          </div>

          <div
            className={`${styles.container} ${styles.image1}`}
            style={{
              backgroundOrigin: "border-box",
              backgroundPosition: "30px 40px",
              backgroundRepeat: "repeat",
            }}
          >
          </div>

          <div
            className={`${styles.container} ${styles.image2}`}
            style={{
              backgroundOrigin: "content-box, border-box",
              backgroundPosition: "50% 40px, right bottom",
              backgroundRepeat: "repeat-y, repeat-x",
            }}
          >
          </div>
        </div>
      </WebFListView>
    </div>
  );
};
