// webf/example/react_use_cases/src/pages/LoadingPage.tsx
import React, { useRef } from 'react';
import { createComponent } from '../utils/CreateComponent';
import styles from './LoadingPage.module.css';

const WebFListView = createComponent({
  tagName: 'webf-listview',
  displayName: 'WebFListView'
});

const FlutterCupertinoButton = createComponent({
  tagName: 'flutter-cupertino-button',
  displayName: 'FlutterCupertinoButton'
});

const FlutterCupertinoLoading = createComponent({
  tagName: 'flutter-cupertino-loading',
  displayName: 'FlutterCupertinoLoading',
  events: {
    onClose: 'close'
  }
});

export const LoadingPage: React.FC = () => {
  const basicLoadingRef = useRef<any>(null);
  const textLoadingRef = useRef<any>(null);
  const autoHideLoadingRef = useRef<any>(null);
  const maskClosableLoadingRef = useRef<any>(null);

  const showBasicLoading = () => {
    basicLoadingRef.current?.show();
    setTimeout(() => {
      basicLoadingRef.current?.hide();
    }, 1000);
  };

  const showLoadingWithText = () => {
    textLoadingRef.current?.show({
      text: 'Loading...'
    });
    setTimeout(() => {
      textLoadingRef.current?.hide();
    }, 1000);
  };

  const showAutoHideLoading = () => {
    autoHideLoadingRef.current?.show({
      text: 'Processing...'
    });
    setTimeout(() => {
      autoHideLoadingRef.current?.hide();
    }, 2000);
  };

  const showMaskClosableLoading = () => {
    maskClosableLoadingRef.current?.show({
      text: 'Click mask to close'
    });
  };

  const handleLoadingClose = () => {
    console.log('Loading closed by mask click');
  };

  return (
    <div id="main">
      <WebFListView className={styles.list}>
        <div className={styles.componentSection}>
          <div className={styles.sectionTitle}>Loading</div>
          <div className={styles.componentBlock}>
            
            {/* Basic Usage */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>Basic Usage</div>
              <FlutterCupertinoButton variant="filled" onClick={showBasicLoading}>
                Show Loading
              </FlutterCupertinoButton>
            </div>

            {/* With Text */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>With Text</div>
              <FlutterCupertinoButton variant="filled" onClick={showLoadingWithText}>
                Show Loading
              </FlutterCupertinoButton>
            </div>

            {/* Auto Hide */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>Auto Hide</div>
              <FlutterCupertinoButton variant="filled" onClick={showAutoHideLoading}>
                Show Loading (Auto hide in 2s)
              </FlutterCupertinoButton>
            </div>

            {/* Mask Closable */}
            <div className={styles.componentItem}>
              <div className={styles.itemLabel}>Mask Closable</div>
              <FlutterCupertinoButton variant="filled" onClick={showMaskClosableLoading}>
                Show Loading (Click mask to close)
              </FlutterCupertinoButton>
            </div>
          </div>
        </div>

        {/* Loading Components */}
        <FlutterCupertinoLoading ref={basicLoadingRef} />
        <FlutterCupertinoLoading ref={textLoadingRef} />
        <FlutterCupertinoLoading ref={autoHideLoadingRef} />
        <FlutterCupertinoLoading ref={maskClosableLoadingRef} maskClosable onClose={handleLoadingClose} />
      </WebFListView>
    </div>
  );
};

// webf_apps/vue-cupertino-gallery-vite/src/Pages/LoadingPage.vue
<template>
  <div id="main">
    <webf-listview id="list">
      <div class="component-section">
        <div class="section-title">Loading</div>
        <div class="component-block">
          <!-- Basic Usage -->
          <div class="component-item">
            <div class="item-label">Basic Usage</div>
            <flutter-cupertino-button variant="filled" @click="showBasicLoading">
              Show Loading
            </flutter-cupertino-button>
          </div>

          <!-- With Text -->
          <div class="component-item">
            <div class="item-label">With Text</div>
            <flutter-cupertino-button variant="filled" @click="showLoadingWithText">
              Show Loading
            </flutter-cupertino-button>
          </div>

          <!-- Auto Hide -->
          <div class="component-item">
            <div class="item-label">Auto Hide</div>
            <flutter-cupertino-button variant="filled" @click="showAutoHideLoading">
              Show Loading (Auto hide in 2s)
            </flutter-cupertino-button>
          </div>

          <!-- Mask Closable -->
          <div class="component-item">
            <div class="item-label">Mask Closable</div>
            <flutter-cupertino-button variant="filled" @click="showMaskClosableLoading">
              Show Loading (Click mask to close)
            </flutter-cupertino-button>
          </div>
        </div>
      </div>

      <!-- Loading Components -->
      <flutter-cupertino-loading ref="basicLoading" />
      <flutter-cupertino-loading ref="textLoading" />
      <flutter-cupertino-loading ref="autoHideLoading" />
      <flutter-cupertino-loading ref="maskClosableLoading" maskClosable />
    </webf-listview>
  </div>
</template>

<script>
export default {
  methods: {
    showBasicLoading() {
      this.$refs.basicLoading.show()
      setTimeout(() => {
        this.$refs.basicLoading.hide()
      }, 1000)
    },
    showLoadingWithText() {
      this.$refs.textLoading.show({
        text: 'Loading...',
      })
      setTimeout(() => {
        this.$refs.textLoading.hide()
      }, 1000)
    },
    showAutoHideLoading() {
      this.$refs.autoHideLoading.show({
        text: 'Processing...',
      })
      setTimeout(() => {
        this.$refs.autoHideLoading.hide()
      }, 2000)
    },
    showMaskClosableLoading() {
      this.$refs.maskClosableLoading.show({
        text: 'Click mask to close',
      })
    },
  },
}
</script>

<style lang="scss" scoped>
#list {
  padding: 10px 0;
  height: 100vh;
  width: 100vw;
  background-color: var(--background-primary);
}

.component-section {
  padding: 16px;
  margin-bottom: 8px;

  .section-title {
    font-size: 20px;
    font-weight: 600;
    color: var(--font-color-primary);
    margin-bottom: 16px;
  }

  .component-block {
    background-color: var(--background-secondary);
    border-radius: 12px;
    padding: 16px;

    .component-item {
      margin-bottom: 24px;

      &:last-child {
        margin-bottom: 0;
      }

      .item-label {
        font-size: 14px;
        color: var(--font-color-secondary);
        margin-bottom: 12px;
      }
    }
  }
}

.button-group {
  display: flex;
  gap: 12px;

  :deep(flutter-cupertino-button) {
    flex: 1;
  }
}
</style>
