// vue_usecases/src/pages/routeDemo/ReportDetailsPage.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useLocation, useParams, WebFRouter } from '@openwebf/vue-router';

const params = useParams();
const location = useLocation();

const reportId = computed(() => {
  const p = params.value as any;
  return params.value.id ?? p.reportId ?? (location.value.state as any)?.reportId;
});
</script>

<template>
  <webf-list-view class="p-5 bg-surface-secondary rounded-xl mb-5 border border-line">
    <h1 class="text-2xl font-semibold mb-4 text-fg-primary">Report Details</h1>

    <div class="mb-5">
      <h2 class="text-lg font-semibold mb-3 text-fg-primary">Report Parameters:</h2>
      <div class="bg-surface-tertiary p-4 rounded-lg border border-line">
        <p class="mb-2 font-mono text-fg"><strong>Year:</strong> {{ params.year || 'Not provided' }}</p>
        <p class="mb-2 font-mono text-fg"><strong>Month:</strong> {{ params.month || 'Not provided' }}</p>
        <p class="mb-0 font-mono text-fg"><strong>Report ID:</strong> {{ reportId || 'Not provided' }}</p>
      </div>
    </div>

    <div class="mb-5">
      <h2 class="text-lg font-semibold mb-3 text-fg-primary">Report Information:</h2>
      <div class="bg-surface-tertiary p-4 rounded-lg border border-line">
        <div class="grid grid-cols-2 gap-4">
          <div>
            <h3 class="text-sm mb-2 text-fg-secondary">Period</h3>
            <p class="text-base m-0 text-fg">{{ params.month || '--' }}/{{ params.year || '--' }}</p>
          </div>
          <div>
            <h3 class="text-sm mb-2 text-fg-secondary">Department</h3>
            <p class="text-base m-0 capitalize text-fg">{{ (location.state as any)?.department || 'Not specified' }}</p>
          </div>
          <div>
            <h3 class="text-sm mb-2 text-fg-secondary">Format</h3>
            <p class="text-base m-0 uppercase text-fg">{{ (location.state as any)?.format || 'Not specified' }}</p>
          </div>
          <div>
            <h3 class="text-sm mb-2 text-fg-secondary">Report ID</h3>
            <p class="text-base m-0 font-mono text-fg">{{ reportId || '--' }}</p>
          </div>
        </div>
      </div>
    </div>

    <div class="mb-5">
      <h2 class="text-lg font-semibold mb-3 text-fg-primary">Navigation State:</h2>
      <div class="bg-surface-tertiary p-4 rounded-lg border border-line">
        <pre class="m-0 text-xs font-mono whitespace-pre-wrap text-fg">{{ JSON.stringify(location.state, null, 2) }}</pre>
      </div>
    </div>

    <div class="flex">
      <button
        class="bg-[#007aff] hover:bg-[#006fe6] text-white border-0 rounded-lg py-3 px-6 text-base cursor-pointer transition-colors active:scale-[.98]"
        @click="WebFRouter.pop()"
      >
        Back
      </button>
    </div>
  </webf-list-view>
</template>

// webf_apps/react_use_cases/src/pages/routeDemo/ReportDetailsPage.tsx
import React from 'react';
import { useParams, useLocation } from '@openwebf/react-router';
import { WebFListView } from '@openwebf/react-core-ui';
import { WebFRouter } from '@openwebf/react-router';

export const ReportDetailsPage: React.FC = () => {
  const params = useParams();
  const location = useLocation();

  return (
    <WebFListView style={{ padding: '20px' }}>
      <div style={{
        backgroundColor: 'var(--background-secondary)',
        borderRadius: '12px',
        padding: '24px',
        marginBottom: '20px',
        border: '1px solid var(--border-color)'
      }}>
        <h1 style={{ 
          fontSize: '24px', 
          marginBottom: '16px',
          color: 'var(--font-color-primary)'
        }}>
          Report Details
        </h1>
        
        <div style={{ marginBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', marginBottom: '12px', color: 'var(--font-color-primary)' }}>
            Report Parameters:
          </h2>
          <div style={{
            backgroundColor: 'var(--background-tertiary)',
            padding: '16px',
            borderRadius: '8px',
            border: '1px solid var(--border-color)'
          }}>
            <p style={{ margin: '0 0 8px 0', fontFamily: 'monospace', color: 'var(--font-color)' }}>
              <strong>Year:</strong> {params.year || 'Not provided'}
            </p>
            <p style={{ margin: '0 0 8px 0', fontFamily: 'monospace', color: 'var(--font-color)' }}>
              <strong>Month:</strong> {params.month || 'Not provided'}
            </p>
            <p style={{ margin: '0 0 8px 0', fontFamily: 'monospace', color: 'var(--font-color)' }}>
              <strong>Report ID:</strong> {params.reportId || 'Not provided'}
            </p>
          </div>
        </div>

        <div style={{ marginBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', marginBottom: '12px', color: 'var(--font-color-primary)' }}>
            Report Information:
          </h2>
          <div style={{
            backgroundColor: 'var(--background-tertiary)',
            padding: '16px',
            borderRadius: '8px',
            border: '1px solid var(--border-color)'
          }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div>
                <h3 style={{ fontSize: '14px', margin: '0 0 8px 0', color: 'var(--secondary-font-color)' }}>Period</h3>
                <p style={{ fontSize: '16px', margin: 0, color: 'var(--font-color)' }}>
                  {params.month}/{params.year}
                </p>
              </div>
              <div>
                <h3 style={{ fontSize: '14px', margin: '0 0 8px 0', color: 'var(--secondary-font-color)' }}>Department</h3>
                <p style={{ fontSize: '16px', margin: 0, textTransform: 'capitalize', color: 'var(--font-color)' }}>
                  {location.state?.department || 'Not specified'}
                </p>
              </div>
              <div>
                <h3 style={{ fontSize: '14px', margin: '0 0 8px 0', color: 'var(--secondary-font-color)' }}>Format</h3>
                <p style={{ fontSize: '16px', margin: 0, textTransform: 'uppercase', color: 'var(--font-color)' }}>
                  {location.state?.format || 'Not specified'}
                </p>
              </div>
              <div>
                <h3 style={{ fontSize: '14px', margin: '0 0 8px 0', color: 'var(--secondary-font-color)' }}>Report ID</h3>
                <p style={{ fontSize: '16px', margin: 0, fontFamily: 'monospace', color: 'var(--font-color)' }}>
                  {params.reportId}
                </p>
              </div>
            </div>
          </div>
        </div>

        <div style={{ marginBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', marginBottom: '12px', color: 'var(--font-color-primary)' }}>
            Navigation State:
          </h2>
          <div style={{
            backgroundColor: 'var(--background-tertiary)',
            padding: '16px',
            borderRadius: '8px',
            border: '1px solid var(--border-color)'
          }}>
            <pre style={{ 
              margin: 0, 
              fontSize: '12px',
              fontFamily: 'monospace',
              whiteSpace: 'pre-wrap',
              color: 'var(--font-color)'
            }}>
              {JSON.stringify(location.state, null, 2)}
            </pre>
          </div>
        </div>

        <div style={{ display: 'flex' }}>
          <button
            onClick={() => WebFRouter.pushState({}, '/')}
            style={{
              background: '#007aff',
              color: 'white',
              border: 'none',
              borderRadius: '8px',
              padding: '12px 24px',
              fontSize: '16px',
              cursor: 'pointer'
            }}
          >
            Back to Home
          </button>
        </div>
      </div>
    </WebFListView>
  );
};
