// vue_usecases/src/pages/routeDemo/UserDetailsPage.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useLocation, useParams, WebFRouter } from '@openwebf/vue-router';

const params = useParams();
const location = useLocation();

const userId = computed(() => params.value.id ?? 'Not provided');
const userType = computed(() => (params.value as any).userType as string | undefined);
</script>

<template>
  <webf-list-view class="p-5 bg-surface-secondary rounded-xl mb-5 border border-line">
    <h1 class="text-2xl font-semibold mb-4 text-fg-primary">User Details</h1>

    <div class="mb-5">
      <h2 class="text-lg font-semibold mb-3 text-fg-primary">Route Parameters:</h2>
      <div class="bg-surface-tertiary p-4 rounded-lg border border-line">
        <p class="mb-2 font-mono text-fg"><strong>userId:</strong> {{ userId }}</p>
        <p v-if="userType" class="font-mono text-fg"><strong>userType:</strong> {{ userType }}</p>
      </div>
    </div>

    <div class="mb-5">
      <h2 class="text-lg font-semibold mb-3 text-fg-primary">Location State:</h2>
      <div class="bg-surface-tertiary p-4 rounded-lg border border-line">
        <pre class="m-0 text-xs font-mono whitespace-pre-wrap text-fg">{{ JSON.stringify(location.state, null, 2) }}</pre>
      </div>
    </div>

    <div class="mb-5">
      <h2 class="text-lg font-semibold mb-3 text-fg-primary">Current Path:</h2>
      <div class="bg-surface-tertiary p-4 rounded-lg border border-line">
        <p class="m-0 font-mono text-fg">{{ location.pathname }}</p>
      </div>
    </div>

    <div class="flex flex-wrap gap-3">
      <button
        class="bg-[#007aff] hover:bg-[#006fe6] text-white border-0 rounded-lg py-3 px-6 text-base cursor-pointer transition-colors active:scale-[.98]"
        @click="WebFRouter.pop()"
      >
        Back
      </button>
      <button
        class="bg-[#007aff] hover:bg-[#006fe6] text-white border-0 rounded-lg py-3 px-6 text-base cursor-pointer transition-colors active:scale-[.98]"
        @click="WebFRouter.pushState({}, '/user/888')"
      >
        Go User Details 888
      </button>
    </div>
  </webf-list-view>
</template>

// webf_apps/react_use_cases/src/pages/routeDemo/UserDetailsPage.tsx
import React from 'react';
import { useParams, useLocation } from '@openwebf/react-router';
import { WebFListView } from '@openwebf/react-core-ui';
import { WebFRouter } from '@openwebf/react-router';

export const UserDetailsPage: React.FC = () => {
  
  const params = useParams();
  const location = useLocation();

  return (
    <WebFListView style={{ padding: '20px' }}>
      <div style={{
        backgroundColor: 'var(--background-secondary)',
        borderRadius: '12px',
        padding: '24px',
        marginBottom: '20px',
        border: '1px solid var(--border-color)'
      }}>
        <h1 style={{ 
          fontSize: '24px', 
          marginBottom: '16px',
          color: 'var(--font-color-primary)'
        }}>
          User Details
        </h1>
        
        <div style={{ marginBottom: '20px' }}>
          <h2 style={{ 
            fontSize: '18px', 
            marginBottom: '12px', 
            color: 'var(--font-color-primary)' 
          }}>
            Route Parameters:
          </h2>
          <div style={{
            backgroundColor: 'var(--background-tertiary)',
            padding: '16px',
            borderRadius: '8px',
            border: '1px solid var(--border-color)'
          }}>
            <p style={{ 
              margin: '0 0 8px 0', 
              fontFamily: 'monospace',
              color: 'var(--font-color)'
            }}>
              <strong>userId:</strong> {params.userId || 'Not provided'}
            </p>
            {params.userType && (
              <p style={{ 
                margin: '0', 
                fontFamily: 'monospace',
                color: 'var(--font-color)'
              }}>
                <strong>userType:</strong> {params.userType}
              </p>
            )}
          </div>
        </div>

        <div style={{ marginBottom: '20px' }}>
          <h2 style={{ 
            fontSize: '18px', 
            marginBottom: '12px', 
            color: 'var(--font-color-primary)' 
          }}>
            Location State:
          </h2>
          <div style={{
            backgroundColor: 'var(--background-tertiary)',
            padding: '16px',
            borderRadius: '8px',
            border: '1px solid var(--border-color)'
          }}>
            <pre style={{ 
              margin: 0, 
              fontSize: '12px',
              fontFamily: 'monospace',
              whiteSpace: 'pre-wrap',
              color: 'var(--font-color)'
            }}>
              {JSON.stringify(location.state, null, 2)}
            </pre>
          </div>
        </div>

        <div style={{ marginBottom: '20px' }}>
          <h2 style={{ 
            fontSize: '18px', 
            marginBottom: '12px', 
            color: 'var(--font-color-primary)' 
          }}>
            Current Path:
          </h2>
          <div style={{
            backgroundColor: 'var(--background-tertiary)',
            padding: '16px',
            borderRadius: '8px',
            border: '1px solid var(--border-color)'
          }}>
            <p style={{ 
              margin: 0, 
              fontFamily: 'monospace',
              color: 'var(--font-color)'
            }}>
              {location.pathname}
            </p>
          </div>
        </div>

        <button
          onClick={() => WebFRouter.pushState({}, '/')}
          style={{
            background: '#007aff',
            color: 'white',
            border: 'none',
            borderRadius: '8px',
            padding: '12px 24px',
            fontSize: '16px',
            cursor: 'pointer'
          }}
        >
          Back to Home
        </button>
        <button
          onClick={() => WebFRouter.pushState({}, '/user/888')}
          style={{
            background: '#007aff',
            color: 'white',
            border: 'none',
            marginLeft: '10px',
            borderRadius: '8px',
            padding: '12px 24px',
            fontSize: '16px',
            cursor: 'pointer'
          }}
        >
          Go User Details 888
        </button>
      </div>
    </WebFListView>
  );
};
