// use_cases/src/pages/RouterDemoAbout.tsx
import React, { useMemo } from 'react';
import { WebFRouter, WebFRouterLink, useLocation } from '../router';
import { joinBase, safeJson } from './RouterDemoUtils';

const basePath = '/routing';

export function RouterDemoAbout() {
  const location = useLocation();
  const stateJson = useMemo(() => safeJson(location.state), [location.state]);

  return (
    <div className="mx-auto max-w-3xl space-y-4 text-left">
      <div className="flex items-start justify-between gap-3">
        <h1 className="text-2xl font-semibold text-fg-primary">About</h1>
        <div className="rounded-lg border border-line px-3 py-2 bg-surface">
          <div className="text-xs text-fg-secondary">Path</div>
          <div className="font-mono text-xs text-fg">{location.pathname}</div>
        </div>
      </div>

      <div className="rounded-lg border border-line p-4 bg-surface space-y-2">
        <div className="text-sm text-fg-secondary">State</div>
        <pre className="overflow-auto rounded bg-black/30 p-3 text-xs text-fg">{stateJson}</pre>
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <WebFRouterLink path={joinBase(basePath, '/')}>
          <div className="rounded-lg bg-white/10 px-4 py-2 text-sm text-fg hover:bg-white/15">Home</div>
        </WebFRouterLink>
        <button
          className="rounded-lg bg-white/10 px-4 py-2 text-sm text-fg hover:bg-white/15"
          onClick={() => WebFRouter.maybePop?.() || WebFRouter.back()}
        >
          Back
        </button>
      </div>
    </div>
  );
}

// vue_usecases/src/components/RouterDemoAbout.vue
<script setup lang="ts">
import { useLocation, useNavigate } from '@openwebf/vue-router';

const location = useLocation();
const nav = useNavigate();
</script>

<template>
  <div class="mx-auto max-w-3xl space-y-4 text-left">
    <h1 class="text-2xl font-semibold">About</h1>
    <p class="text-sm opacity-80">A static route at <code>/about</code>.</p>

    <div class="rounded-lg border border-white/10 p-4">
      <div class="text-sm opacity-80">Location</div>
      <div class="mt-1 font-mono text-sm">{{ location.pathname }}</div>
    </div>

    <div class="flex gap-3">
      <button class="rounded-lg bg-white/10 px-4 py-2 text-sm hover:bg-white/15" @click="nav.navigate('/')">
        Go home
      </button>
      <button class="rounded-lg bg-white/10 px-4 py-2 text-sm hover:bg-white/15" @click="nav.navigate(-1)">
        Back
      </button>
    </div>
  </div>
</template>
