// use_cases/src/pages/RouterDemoNotFound.tsx
import React, { useMemo, useState } from 'react';
import { WebFRouter, WebFRouterLink, useLocation } from '../router';
import { joinBase, safeJson } from './RouterDemoUtils';

const basePath = '/routing';

export function RouterDemoNotFound() {
  const location = useLocation();
  const stateJson = useMemo(() => safeJson(location.state), [location.state]);
  const [tryPath, setTryPath] = useState('/routing/does-not-exist');

  return (
    <div className="mx-auto max-w-3xl space-y-4 text-left">
      <div className="flex items-start justify-between gap-3">
        <h1 className="text-2xl font-semibold text-fg-primary">Not Found</h1>
        <div className="rounded-lg border border-line px-3 py-2 bg-surface">
          <div className="text-xs text-fg-secondary">Path</div>
          <div className="font-mono text-xs text-fg">{location.pathname}</div>
        </div>
      </div>

      <div className="rounded-lg border border-line p-4 bg-surface space-y-2">
        <div className="text-sm text-fg-secondary">State</div>
        <pre className="overflow-auto rounded bg-black/30 p-3 text-xs text-fg">{stateJson}</pre>
      </div>

      <div className="rounded-lg border border-line p-4 bg-surface space-y-3">
        <div className="text-sm font-semibold text-fg-primary">Try another missing path</div>
        <div className="flex gap-2">
          <input
            className="flex-1 rounded-md border border-line bg-surface px-3 py-2 text-sm text-fg"
            value={tryPath}
            onChange={(e) => setTryPath(e.target.value)}
          />
          <button
            className="rounded-md bg-blue-500/70 px-4 py-2 text-sm text-white hover:bg-blue-500/80"
            onClick={() => WebFRouter.replace(tryPath, { from: location.pathname, at: Date.now() })}
          >
            Go
          </button>
        </div>
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <WebFRouterLink path={joinBase(basePath, '/')}>
          <div className="rounded-lg bg-white/10 px-4 py-2 text-sm text-fg hover:bg-white/15">Home</div>
        </WebFRouterLink>
        <WebFRouterLink path={joinBase(basePath, '/users/1')}>
          <div className="rounded-lg bg-white/10 px-4 py-2 text-sm text-fg hover:bg-white/15">User #1</div>
        </WebFRouterLink>
        <WebFRouterLink path={joinBase(basePath, '/files/docs/getting-started')}>
          <div className="rounded-lg bg-white/10 px-4 py-2 text-sm text-fg hover:bg-white/15">Files</div>
        </WebFRouterLink>
        <button
          className="rounded-lg bg-white/10 px-4 py-2 text-sm text-fg hover:bg-white/15"
          onClick={() => WebFRouter.maybePop?.() || WebFRouter.back()}
        >
          Back
        </button>
      </div>
    </div>
  );
}

// vue_usecases/src/components/RouterDemoNotFound.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useLocation, useNavigate, useParams, useRouteContext } from '@openwebf/vue-router';

const props = withDefaults(
  defineProps<{
    basePath?: string;
  }>(),
  {
    basePath: '',
  },
);

function joinBase(path: string) {
  if (!props.basePath) return path;
  const base = props.basePath.endsWith('/') ? props.basePath.slice(0, -1) : props.basePath;
  const suffix = path.startsWith('/') ? path : `/${path}`;
  return `${base}${suffix}`.replace(/\/{2,}/g, '/');
}

const nav = useNavigate();
const params = useParams();
const location = useLocation();
const route = useRouteContext();

const caught = computed(() => params.value['*'] ?? '(missing)');

const currentStateJson = computed(() => {
  const state = location.value.state;
  if (state === undefined) return 'undefined';
  try {
    return JSON.stringify(state, null, 2);
  } catch {
    return String(state);
  }
});

const tryPath = ref('somewhere/else');

function goTryPath() {
  nav.navigate(joinBase(`/${tryPath.value}`));
}
</script>

<template>
  <div class="mx-auto max-w-3xl space-y-4 text-left">
    <div class="flex items-start justify-between gap-3">
      <h1 class="text-2xl font-semibold">Not Found</h1>
      <div class="rounded-lg border border-white/10 px-3 py-2">
        <div class="text-xs opacity-70">Path</div>
        <div class="font-mono text-xs">{{ location.pathname }}</div>
      </div>
    </div>
    <p class="text-sm opacity-80">
      Catch-all route <code>{{ joinBase('/*') }}</code> captures the entire pathname into <code>params["*"]</code>.
    </p>

    <div class="rounded-lg border border-white/10 p-4 space-y-2">
      <div class="text-sm opacity-80">Route</div>
      <div class="grid gap-1 font-mono text-sm">
        <div><span class="opacity-70">pattern:</span> {{ route.path }}</div>
        <div><span class="opacity-70">mounted:</span> {{ route.mountedPath }}</div>
        <div><span class="opacity-70">active:</span> {{ route.activePath }}</div>
      </div>
    </div>

    <div class="rounded-lg border border-white/10 p-4 space-y-2">
      <div class="text-sm opacity-80">Captured</div>
      <div class="font-mono text-sm">{{ caught }}</div>
    </div>

    <div class="rounded-lg border border-white/10 p-4 space-y-2">
      <div class="text-sm opacity-80">State</div>
      <pre class="overflow-auto rounded bg-black/30 p-3 text-xs">{{ currentStateJson }}</pre>
    </div>

    <div class="rounded-lg border border-white/10 p-4 space-y-2">
      <div class="text-sm opacity-80">Try another missing path</div>
      <div class="flex gap-2">
        <input
          v-model="tryPath"
          class="w-full rounded bg-black/20 px-3 py-2 text-sm outline-none ring-1 ring-white/10 focus:ring-white/20"
          placeholder="unknown path (e.g. foo/bar)"
        />
        <button class="rounded-lg bg-blue-500/70 px-4 py-2 text-sm hover:bg-blue-500/80" @click="goTryPath">
          Go
        </button>
      </div>
    </div>

    <div class="grid gap-3 sm:grid-cols-2">
      <button class="rounded-lg bg-white/10 px-4 py-2 text-sm hover:bg-white/15" @click="nav.navigate(joinBase('/'))">
        Home
      </button>
      <button class="rounded-lg bg-white/10 px-4 py-2 text-sm hover:bg-white/15" @click="nav.navigate(-1)">
        Back
      </button>
    </div>
  </div>
</template>
