// use_cases/src/pages/RoutingPage.tsx
import React from 'react';
import { RoutingDemoShell } from './RoutingDemoShell';
import { RouterDemoHome } from './RouterDemoHome';

export const RoutingPage: React.FC = () => {
  return (
    <RoutingDemoShell
      title="Routing & Navigation"
      description="Router demos rendered inside a scrollable WebFListView. Navigate within /routing/*."
    >
      <RouterDemoHome />
    </RoutingDemoShell>
  );
};

// vue_usecases/src/pages/RoutingPage.vue
<script setup lang="ts">
import RouterDemoHome from '../components/RouterDemoHome.vue';
import RoutingDemoShell from './routing/_shared/RoutingDemoShell.vue';
</script>

<template>
  <RoutingDemoShell
    title="Routing & Navigation"
    description="Router demos rendered inside a scrollable webf-list-view. Navigate within /routing/*."
    :demo="RouterDemoHome"
  />
</template>
