// webf_apps/vue-cupertino-gallery/src/components/RouterView.vue
<template>
    <webf-router-link :path="path" @onscreen="onScreen" :title="title">
      <slot v-if="isMounted"></slot>
    </webf-router-link>
  </template>

  <script>
  export default {
    name: 'RouterView',
    props: {
      path: {
        type: String,
        required: true,
      },
      title: {
        type: String
      }
    },
    data() {
      return {
        isMounted: false,
      }
    },
    methods: {
      onScreen() {
        this.isMounted = true;
      }
    }
  }
  </script>

// webf/example/react_use_cases/src/components/RouterView.tsx
import React, { useState, ReactNode } from 'react';
import { createComponent } from '../utils/CreateComponent';

interface RouterViewProps {
  path: string;
  title?: string;
  children?: ReactNode;
}

const WebFRouterLink = createComponent({
  tagName: 'webf-router-link',
  displayName: 'WebFRouterLink',
  events: {
    onOnScreen: 'onscreen'
  }
});

export const RouterView: React.FC<RouterViewProps> = ({ path, title, children }) => {
  const [isMounted, setIsMounted] = useState(false);

  const handleOnScreen = () => {
    setIsMounted(true);
  };

  return (
    <WebFRouterLink path={path} title={title} onOnScreen={handleOnScreen}>
      {isMounted ? children : null}
    </WebFRouterLink>
  );
};
